# Generated by Django 5.0.7 on 2024-07-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Введіть ім'я автора", max_length=100, verbose_name="Ім'я автора")),
                ('last_name', models.CharField(help_text='Введіть прізвище автора', max_length=100, verbose_name='Прізвище автора')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введіт дату народження', null=True, verbose_name='Дата народження')),
                ('date_of_death', models.DateField(blank=True, help_text='Введіть дату смерті', null=True, verbose_name='Дата смерті')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Введіть жанр книги', max_length=200, verbose_name='Жанр книги')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Введіть мову книги', max_length=20, verbose_name='Мова книги')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть статус екземпляра книги', max_length=20, verbose_name='Статус екземпляра книги')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=' Введіть назву книги', max_length=200, verbose_name='Назва книги')),
                ('summary', models.TextField(help_text='Введіть аннотацію книги', max_length=1000, verbose_name='Аннотація книги')),
                ('isbn', models.CharField(help_text='Повинно містити 13 символів', max_length=13, verbose_name=' ISBN книги')),
                ('author', models.ManyToManyField(help_text=' Оберіть автора книги', null=True, to='catalog.author', verbose_name='Автор книги')),
                ('genre', models.ForeignKey(help_text=' Оберіть жанр книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Жанр книги')),
                ('language', models.ForeignKey(help_text=' Оберіть мову книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Мова книги')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Введіть інвентерезаційний номер', max_length=20, verbose_name='інвентерезаційний номер')),
                ('imprint', models.CharField(help_text='Введіть назву видавництва і рік', max_length=200, verbose_name='Видавництво')),
                ('due_back', models.DateField(help_text='Введіть кінець строку стану', null=True, verbose_name='Дата закцінчення статусу')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Змінити стан екземпляра', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Стан екземпляра')),
            ],
        ),
    ]
