# Generated by Django 5.0.7 on 2024-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text=' Оберіть автора книги', to='catalog.author', verbose_name='Автор книги'),
        ),
    ]
